# Test 2024-10-25 at 00:31:08

name: Test
run-name: bartok

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [BitMachine, Chip, Layout, Mjaf, Stuck, Test, Unary]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp `find .  -name "*.java"` com/AppaApps/Silicon

    - name: Files
      run:
        tree

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes `find com/AppaApps/Silicon -name "*.java"`

    - name: Test BitMachine
      if: matrix.task == 'BitMachine'
      run: |
        java -cp Classes com/AppaApps/Silicon/BitMachine

    - name: Test Chip
      if: matrix.task == 'Chip'
      run: |
        java -cp Classes com/AppaApps/Silicon/Chip

    - name: Test Layout
      if: matrix.task == 'Layout'
      run: |
        java -cp Classes com/AppaApps/Silicon/Layout

    - name: Test Mjaf
      if: matrix.task == 'Mjaf'
      run: |
        java -cp Classes com/AppaApps/Silicon/Mjaf

    - name: Test Stuck
      if: matrix.task == 'Stuck'
      run: |
        java -cp Classes com/AppaApps/Silicon/Stuck

    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -cp Classes com/AppaApps/Silicon/Test

    - name: Test Unary
      if: matrix.task == 'Unary'
      run: |
        java -cp Classes com/AppaApps/Silicon/Unary
