# Test 2024-09-22 at 08:04:55

name: Test
run-name: bartok

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Chip, Test]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Position
      run: |
        mkdir -p com/AppaApps/Silicon
        cp `find . -name "*.java"` com/AppaApps/Silicon

    - name: Files
      run:
        tree

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes `find com/AppaApps/Silicon -name "*.java"`

    - name: Test Chip
      if: matrix.task == 'Chip'
      run: |
        java -cp Classes com/AppaApps/Silicon/Chip

    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -cp Classes com/AppaApps/Silicon/Test
